### ISSUE TITLE
getStyles should check if element is undefined

### ISSUE THREAD

**Issue by fsmanuel** [paddle8/dom-ruler#4]
I encountered the problem when i used `ember-popup-menu` and forgot to add `<span class="popup-menu_pointer"></span>` to the component template.

The Error is:
```
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```
and points to https://github.com/paddle8/dom-ruler/blob/master/lib/dom-ruler/styles.js#L45

**Comment by tim-evans** [comment]
Fixed as of 0.1.7 :)
